#!/usr/bin/env python3
"""
SeRTial Message Schema Visualizer

Reads JSON schema files generated by schema_generator and displays:
- Memory layout before/after serialization
- Copy blocks with different colors
- Padding analysis
- Summary statistics
"""

import json
import sys
import argparse
from dataclasses import dataclass
from typing import List, Optional
from pathlib import Path

# ANSI color codes for terminal output
class Colors:
    RESET = '\033[0m'
    BOLD = '\033[1m'
    DIM = '\033[2m'
    
    # Field colors (cycle through these for different fields)
    FIELD_COLORS = [
        '\033[48;5;31m',   # Blue
        '\033[48;5;35m',   # Green  
        '\033[48;5;136m',  # Yellow/Orange
        '\033[48;5;132m',  # Magenta
        '\033[48;5;37m',   # Cyan
        '\033[48;5;167m',  # Red
        '\033[48;5;98m',   # Purple
        '\033[48;5;29m',   # Teal
    ]
    
    PADDING = '\033[48;5;236m'  # Dark gray for padding
    HEADER = '\033[48;5;240m'   # Medium gray for headers
    
    # Text colors
    WHITE = '\033[97m'
    BLACK = '\033[30m'
    GREEN = '\033[92m'
    RED = '\033[91m'
    YELLOW = '\033[93m'
    CYAN = '\033[96m'


@dataclass
class FieldInfo:
    name: str
    type: str
    offset: int
    size: int
    packed_size: int
    has_padding_after: bool
    padding_bytes: int


@dataclass
class CopyBlock:
    source_offset: int
    dest_offset: int
    size: int
    description: str


@dataclass
class MessageSchema:
    name: str
    category: str
    sizeof_bytes: int
    packed_size: int
    max_serialized_size: int
    has_padding: bool
    is_bounded: bool
    can_memcpy_whole: bool
    fields: List[FieldInfo]
    copy_blocks: List[CopyBlock]
    num_copy_operations: int
    size_category: str


def load_schemas(filepath: str) -> dict:
    """Load schemas from JSON file."""
    with open(filepath, 'r') as f:
        return json.load(f)


def parse_message(data: dict) -> MessageSchema:
    """Parse a message schema from JSON data."""
    fields = [
        FieldInfo(
            name=f.get('name', ''),
            type=f.get('type', ''),
            offset=f.get('offset', 0),
            size=f.get('size', 0),
            packed_size=f.get('packed_size', 0),
            has_padding_after=f.get('has_padding_after', False),
            padding_bytes=f.get('padding_bytes', 0)
        )
        for f in data.get('fields', [])
    ]
    
    copy_blocks = [
        CopyBlock(
            source_offset=b.get('source_offset', 0),
            dest_offset=b.get('dest_offset', 0),
            size=b.get('size', 0),
            description=b.get('description', '')
        )
        for b in data.get('copy_blocks', [])
    ]
    
    return MessageSchema(
        name=data.get('name', ''),
        category=data.get('category', ''),
        sizeof_bytes=data.get('sizeof_bytes', 0),
        packed_size=data.get('packed_size', 0),
        max_serialized_size=data.get('max_serialized_size', 0),
        has_padding=data.get('has_padding', False),
        is_bounded=data.get('is_bounded', False),
        can_memcpy_whole=data.get('can_memcpy_whole', False),
        fields=fields,
        copy_blocks=copy_blocks,
        num_copy_operations=data.get('num_copy_operations', 0),
        size_category=data.get('size_category', '')
    )


def render_memory_bar(size: int, regions: List[tuple], width: int = 60, label: str = "") -> str:
    """
    Render a memory bar with colored regions.
    regions: List of (start, length, color_index, label)
    """
    if size == 0:
        return f"{label}: [empty]"
    
    # Build character array
    bar = ['░'] * width  # Default: unused/padding
    colors = [Colors.PADDING] * width
    
    for start, length, color_idx, _ in regions:
        if length == 0:
            continue
        start_pos = int(start * width / size)
        end_pos = int((start + length) * width / size)
        end_pos = max(end_pos, start_pos + 1)  # At least 1 char
        
        color = Colors.FIELD_COLORS[color_idx % len(Colors.FIELD_COLORS)]
        for i in range(start_pos, min(end_pos, width)):
            bar[i] = '█'
            colors[i] = color
    
    # Build output string
    result = f"{label}: ["
    current_color = None
    for i, (char, color) in enumerate(zip(bar, colors)):
        if color != current_color:
            if current_color is not None:
                result += Colors.RESET
            result += color
            current_color = color
        result += char
    result += Colors.RESET + "]"
    
    return result


def visualize_message(msg: MessageSchema, use_color: bool = True):
    """Visualize a single message's memory layout."""
    C = Colors if use_color else type('NoColor', (), {k: '' for k in dir(Colors) if not k.startswith('_')})()
    
    print(f"\n{C.BOLD}{'=' * 70}{C.RESET}")
    print(f"{C.BOLD}{C.CYAN}{msg.name}{C.RESET} ({msg.category})")
    print(f"{'=' * 70}")
    
    # Basic stats
    bounded_str = f"{C.GREEN}[OK] Bounded{C.RESET}" if msg.is_bounded else f"{C.RED}[X] Unbounded{C.RESET}"
    padding_str = f"{C.YELLOW}Has Padding{C.RESET}" if msg.has_padding else f"{C.GREEN}No Padding{C.RESET}"
    
    print(f"\n{C.BOLD}Memory Info:{C.RESET}")
    print(f"  sizeof:           {msg.sizeof_bytes:6} bytes")
    print(f"  packed_size:      {msg.packed_size:6} bytes")
    print(f"  max_serialized:   {msg.max_serialized_size:6} bytes")
    print(f"  size_category:    {msg.size_category}")
    print(f"  status:           {bounded_str}  {padding_str}")
    
    if msg.has_padding:
        savings = msg.sizeof_bytes - msg.packed_size
        pct = (savings / msg.sizeof_bytes * 100) if msg.sizeof_bytes > 0 else 0
        print(f"  padding_savings:  {savings} bytes ({pct:.1f}%)")
    
    # Fields table
    if msg.fields:
        print(f"\n{C.BOLD}Fields:{C.RESET}")
        print(f"  {'#':>2}  {'Name':<20} {'Type':<25} {'Offset':>6} {'Size':>6} {'Packed':>6}")
        print(f"  {'-'*2}  {'-'*20} {'-'*25} {'-'*6} {'-'*6} {'-'*6}")
        
        for i, field in enumerate(msg.fields):
            color = Colors.FIELD_COLORS[i % len(Colors.FIELD_COLORS)] if use_color else ''
            print(f"  {color}{i:>2}{C.RESET}  {field.name:<20} {field.type:<25} {field.offset:>6} {field.size:>6} {field.packed_size:>6}")
            if field.has_padding_after and field.padding_bytes > 0:
                print(f"      {C.DIM}^ {field.padding_bytes} bytes padding before this field{C.RESET}")
    
    # Memory layout visualization
    if msg.fields and msg.sizeof_bytes > 0:
        print(f"\n{C.BOLD}Memory Layout (struct):{C.RESET}")
        
        # Build regions for original struct
        struct_regions = []
        for i, field in enumerate(msg.fields):
            struct_regions.append((field.offset, field.size, i, field.name))
        
        print("  " + render_memory_bar(msg.sizeof_bytes, struct_regions, 60, f"{msg.sizeof_bytes:>4}B"))
        
        # Legend
        print(f"\n  Legend: ", end="")
        for i, field in enumerate(msg.fields[:6]):  # Show first 6 fields
            color = Colors.FIELD_COLORS[i % len(Colors.FIELD_COLORS)] if use_color else ''
            print(f"{color}██{C.RESET}={field.name} ", end="")
        if len(msg.fields) > 6:
            print("...", end="")
        print(f"  {C.PADDING}░░{C.RESET}=padding")
    
    # Serialized layout
    if msg.copy_blocks and msg.max_serialized_size > 0:
        print(f"\n{C.BOLD}Serialized Layout:{C.RESET}")
        
        # Header region
        serial_regions = [(0, 4, -1, "header")]  # 4-byte length header
        
        for i, block in enumerate(msg.copy_blocks):
            serial_regions.append((block.dest_offset, block.size, i, block.description))
        
        # Use different color for header
        header_bar = render_memory_bar(msg.max_serialized_size, serial_regions, 60, f"{msg.max_serialized_size:>4}B")
        print("  " + header_bar)
        print(f"  {C.HEADER}██{C.RESET}=length_header (4B)")
    
    # Copy operations
    if msg.copy_blocks:
        print(f"\n{C.BOLD}Copy Operations ({msg.num_copy_operations}):{C.RESET}")
        for i, block in enumerate(msg.copy_blocks[:8]):  # Show first 8
            color = Colors.FIELD_COLORS[i % len(Colors.FIELD_COLORS)] if use_color else ''
            print(f"  {color}█{C.RESET} {block.description:<15} src[{block.source_offset:>4}:{block.source_offset + block.size:<4}] → dst[{block.dest_offset:>4}:{block.dest_offset + block.size:<4}] ({block.size} bytes)")
        if len(msg.copy_blocks) > 8:
            print(f"  ... and {len(msg.copy_blocks) - 8} more")


def print_summary(messages: List[MessageSchema], use_color: bool = True):
    """Print overall summary statistics."""
    C = Colors if use_color else type('NoColor', (), {k: '' for k in dir(Colors) if not k.startswith('_')})()
    
    print(f"\n{C.BOLD}{'=' * 70}{C.RESET}")
    print(f"{C.BOLD}{C.CYAN}SUMMARY{C.RESET}")
    print(f"{'=' * 70}")
    
    total = len(messages)
    bounded = sum(1 for m in messages if m.is_bounded)
    padded = sum(1 for m in messages if m.has_padding)
    
    # Category breakdown
    categories = {}
    for m in messages:
        cat = m.category
        if cat not in categories:
            categories[cat] = []
        categories[cat].append(m)
    
    print(f"\n{C.BOLD}By Category:{C.RESET}")
    for cat, msgs in sorted(categories.items()):
        print(f"  {cat}: {len(msgs)} messages")
    
    print(f"\n{C.BOLD}Statistics:{C.RESET}")
    print(f"  Total messages:     {total}")
    print(f"  Bounded:            {bounded}/{total} ({bounded/total*100:.1f}%)")
    print(f"  With padding:       {padded}/{total} ({padded/total*100:.1f}%)")
    
    # Size analysis
    sizes = [(m.name, m.sizeof_bytes, m.packed_size, m.max_serialized_size) for m in messages]
    sizes.sort(key=lambda x: x[3], reverse=True)
    
    print(f"\n{C.BOLD}Largest Messages (by max_serialized_size):{C.RESET}")
    print(f"  {'Name':<25} {'sizeof':>8} {'packed':>8} {'max_ser':>10}")
    print(f"  {'-'*25} {'-'*8} {'-'*8} {'-'*10}")
    for name, sz, packed, max_ser in sizes[:10]:
        print(f"  {name:<25} {sz:>8} {packed:>8} {max_ser:>10}")
    
    # Padding savings
    total_sizeof = sum(m.sizeof_bytes for m in messages)
    total_packed = sum(m.packed_size for m in messages)
    savings = total_sizeof - total_packed
    
    print(f"\n{C.BOLD}Padding Analysis:{C.RESET}")
    print(f"  Total struct size:  {total_sizeof} bytes")
    print(f"  Total packed size:  {total_packed} bytes")
    print(f"  Padding eliminated: {savings} bytes ({savings/total_sizeof*100:.1f}%)")


def main():
    parser = argparse.ArgumentParser(description='SeRTial Message Schema Visualizer')
    parser.add_argument('schema_file', nargs='?', default='message_schemas.json',
                        help='JSON schema file (default: message_schemas.json)')
    parser.add_argument('-m', '--message', help='Show only specific message by name')
    parser.add_argument('-c', '--category', help='Filter by category (geometry, sensor)')
    parser.add_argument('-s', '--summary', action='store_true', help='Show only summary')
    parser.add_argument('--no-color', action='store_true', help='Disable colors')
    parser.add_argument('-l', '--list', action='store_true', help='List all message names')
    
    args = parser.parse_args()
    
    # Load schemas
    try:
        data = load_schemas(args.schema_file)
    except FileNotFoundError:
        print(f"Error: Could not find schema file: {args.schema_file}")
        print("Run the schema_generator first to create it.")
        sys.exit(1)
    except json.JSONDecodeError as e:
        print(f"Error: Invalid JSON in {args.schema_file}: {e}")
        sys.exit(1)
    
    messages = [parse_message(m) for m in data.get('messages', [])]
    
    use_color = not args.no_color and sys.stdout.isatty()
    
    # List mode
    if args.list:
        print("Available messages:")
        for m in messages:
            status = "[OK]" if m.is_bounded else "[X]"
            print(f"  [{status}] {m.category}/{m.name}")
        sys.exit(0)
    
    # Filter messages
    if args.message:
        messages = [m for m in messages if args.message.lower() in m.name.lower()]
        if not messages:
            print(f"No messages found matching: {args.message}")
            sys.exit(1)
    
    if args.category:
        messages = [m for m in messages if m.category.lower() == args.category.lower()]
        if not messages:
            print(f"No messages found in category: {args.category}")
            sys.exit(1)
    
    # Print header
    print(f"\n{'=' * 70}")
    print(f"SeRTial Message Schema Visualizer")
    print(f"Generated: {data.get('generated_at', 'unknown')}")
    print(f"Version: {data.get('generator_version', 'unknown')}")
    print(f"{'=' * 70}")
    
    # Summary only mode
    if args.summary:
        print_summary(messages, use_color)
        sys.exit(0)
    
    # Visualize each message
    for msg in messages:
        visualize_message(msg, use_color)
    
    # Always show summary at the end
    print_summary(messages, use_color)


if __name__ == '__main__':
    main()
